# Generated by Django 4.0.4 on 2022-05-10 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, verbose_name='Name')),
                ('car_number', models.SlugField(max_length=254, unique=True, verbose_name='Registration number')),
                ('speed', models.IntegerField(verbose_name='Speed (km/h)')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=254, verbose_name='Username')),
                ('session', models.CharField(blank=True, max_length=100, verbose_name='Session')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance (km)')),
                ('travel_time', models.FloatField(blank=True, null=True, verbose_name='Travel time (h)')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='journey.car', verbose_name='Car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='journey.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Journey',
                'verbose_name_plural': 'Journeys',
            },
        ),
    ]
